POST http://localhost:5000/api/users
Content-Type: application/json

{
  "firstName": "Test2",
  "lastName": "Testovych",
  "email": "test1@test.com",
  "birthday": "1990-01-02",
  "gender": "male",
  "isMerried": true,
  "workExperience": 0
}
GET http://localhost:5000/api/users?limit=10

GET http://localhost:5000/api/users/644e7208af67d3680fd3f58b

PATCH http://localhost:5000/api/users/644e7208af67d3680fd3f58b
Content-Type: application/json

{
  "email": "test3@test.com"
}

DELETE http://localhost:5000/api/users/644e7208af67d3680fd3f58b

POST http://localhost:5000/api/users/6454ecee2567035abdcc362a/posts
Content-Type: application/json

{
  "body":"Some new post 1"
}

GET http://localhost:5000/api/users/6454ecee2567035abdcc362a/posts

GET http://localhost:5000/api/posts


